/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.{html,js}"],
  theme: {
    fontFamily: {
      anton: ["Anton", "sans-serif"],
      manrope: ["Manrope", "sans-serif"],
    },
    extend: {
      fontSize: {
        'vw-1': '1vw',
        'vw-2': '2vw',
        'vw-3': '3vw',
        'vw-4': '4vw',
        'vw-5': '5vw',
      },
      height: {
        'vw-1': '1vw',
        'vw-2': '2vw',
        'vw-3': '3vw',
        'vw-4': '4vw',
        'vw-5': '5vw',
        'vw-6': '6vw',
        'vw-7': '7vw',
        'vw-8': '8vw',
        'vw-9': '9vw',
        'vw-10': '10vw',
        'vw-11': '11vw',
        'vw-12': '12vw',
        'vw-13': '13vw',
        'vw-14': '14vw',
        'vw-15': '15vw',
      },
      width: {
        'vw-1': '1vw',
        'vw-2': '2vw',
        'vw-3': '3vw',
        'vw-4': '4vw',
        'vw-5': '5vw',
        'vw-6': '6vw',
        'vw-7': '7vw',
        'vw-8': '8vw',
        'vw-9': '9vw',
        'vw-10': '10vw',
        'vw-11': '11vw',
        'vw-12': '12vw',
        'vw-13': '13vw',
        'vw-14': '14vw',
        'vw-15': '15vw',
        'vw-16': '16vw',
        'vw-17': '17vw',
        'vw-18': '18vw',
        'vw-19': '19vw',
        'vw-20': '20vw',
        'vw-21': '21vw',
        'vw-22': '22vw',
        'vw-23': '23vw',
        'vw-24': '24vw',
        'vw-25': '25vw',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms')
  ],
}

